### ISSUE TITLE
error: 'timer_isr_callback_add'

### ISSUE THREAD

**Issue by puhycz** [khoih-prog/ESP32_New_ISR_Servo#1]
Hello,

I try use it on ESP32 board. Please help, why dont work for me?

Thanx,

Jan

`.pio\libdeps\Windows\ESP32_New_ISR_Servo\src\ESP32_New_FastTimerInterrupt.h:287:100: error: 'timer_isr_callback_add' was not declared in this scope   
         timer_isr_callback_add(_timerGroup, _timerIndex, _callback, (void *) (uint32_t) _timerNo, 0);
                                                                                                    ^
.pio\libdeps\Windows\ESP32_New_ISR_Servo\src\ESP32_New_FastTimerInterrupt.h: In member function 'void ESP32FastTimerInterrupt::detachInterrupt()':    
.pio\libdeps\Windows\ESP32_New_ISR_Servo\src\ESP32_New_FastTimerInterrupt.h:317:66: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                  ^
.pio\libdeps\Windows\ESP32_New_ISR_Servo\src\ESP32_New_FastTimerInterrupt.h:317:82: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                  ^
.pio\libdeps\Windows\ESP32_New_ISR_Servo\src\ESP32_New_FastTimerInterrupt.h: In member function 'void ESP32FastTimerInterrupt::reattachInterrupt()':  
.pio\libdeps\Windows\ESP32_New_ISR_Servo\src\ESP32_New_FastTimerInterrupt.h:329:65: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                 ^
.pio\libdeps\Windows\ESP32_New_ISR_Servo\src\ESP32_New_FastTimerInterrupt.h:329:81: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);`

**Comment by khoih-prog** [comment]
You have to follow the [**Prerequisites**](https://github.com/khoih-prog/ESP32_New_ISR_Servo#prerequisites) and use the ESP32 core 2.0.0+, for example the latest v2.0.1

Good Luck,
